# config.yaml

# 1. Data Preprocessing Configuration
data_preprocessing:
  image_dir: 'sample_data/images'
  
  # Data Splitting
  split_ratios:
    train: 0.8
    validation: 0.1
    test: 0.1
  random_state: 42

  # Image Preprocessing
  image_size: [128, 128]
  
  # Data Augmentation
  augmentation:
    random_flip_left_right: true
    random_flip_up_down: true
    random_brightness_delta: 0.1
    random_contrast_lower: 0.9
    random_contrast_upper: 1.1

  # Dataset Creation
  batch_size: 32

# 2. Model Training Configuration
model_training:
  # Model Architecture
  model:
    input_shape: [128, 128, 3]
    layers:
      - type: 'Conv2D'
        filters: 32
        kernel_size: [3, 3]
        activation: 'relu'
      - type: 'MaxPooling2D'
        pool_size: [2, 2]
      - type: 'Conv2D'
        filters: 64
        kernel_size: [3, 3]
        activation: 'relu'
      - type: 'MaxPooling2D'
        pool_size: [2, 2]
      - type: 'Conv2D'
        filters: 128
        kernel_size: [3, 3]
        activation: 'relu'
      - type: 'MaxPooling2D'
        pool_size: [2, 2]
      - type: 'Flatten'
      - type: 'Dense'
        units: 128
        activation: 'relu'
      - type: 'Dense'
        # units will be set dynamically based on number of classes
        activation: 'softmax'

  # Compilation
  compiler:
    optimizer: 'adam'
    loss: 'sparse_categorical_crossentropy'
    metrics: ['accuracy']

  # Training
  epochs: 2
  
  # Checkpoint
  checkpoint:
    filepath: 'best_model.keras'
    monitor: 'val_accuracy'
    mode: 'max'

# 3. Result Analysis Configuration
result_analysis:
  model_path: 'best_model.keras'
  plot_history: true
  confusion_matrix:
    enabled: true
    figsize: [5, 4]
    cmap: 'Blues'
